id: A44532A16
title: 'Self-Arising Wisdom: Songtsen Gampo Guru SÄdhana'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:52.082239
  last_modified_at: 2022-03-01 03:51:52.082242
