id: A44532A16
title: Guru Sādhana of Glorious Dharmakīrti
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:52.079829
  last_modified_at: 2022-03-01 03:51:52.079833
