id: A44532A16
title: SÄdhana of the Great Master Vairotsana
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:51:52.083306
  last_modified_at: 2022-03-01 03:51:52.083309
